c_compiler_version:    # [osx]
- '12'                 # [osx]
cxx_compiler_version:  # [osx]
- '12'                 # [osx]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.12"                # [osx and x86_64]
